# my global config
global:
  scrape_interval:     15s
  evaluation_interval: 30s
  # scrape_timeout is set to the global default (10s).

scrape_configs:
- job_name: prometheus

  honor_labels: true
  # scrape_interval is defined by the configured global (15s).
  # scrape_timeout is defined by the global default (10s).

  # metrics_path defaults to '/metrics'
  # scheme defaults to 'http'.

  static_configs:
  # - targets: ['localhost:9090', 'localhost:9191']
    - targets: ['localhost:9090']
      labels:
        service: prometheus


- job_name: redis_exporter
  static_configs:
    - targets: ['127.0.0.1:9121']
      labels:
        service: redis

- job_name: postgres_exporter
  static_configs:
    - targets: ['127.0.0.1:9187']
      labels:
        service: postgres

- job_name: nginx_exporter
  static_configs:
    - targets: ['127.0.0.1:9145']
      labels:
        service: nginx
        role: lua-app
